/**
 * 9 built-in scenarios (seed data). Each is valid per Scenario Schema.
 * @module scenarios/builtins
 */
import type { Scenario } from './schema';

const box = {
  volume: 'box',
  halfExtents: { x: 6, y: 4, z: 0.5 },
  minDistance: 10,
  maxDistance: 18,
} as const;
const cone = { volume: 'cone', coneHalfAngleDeg: 14, minDistance: 10, maxDistance: 22 } as const;

export const BUILT_IN_SCENARIOS: Scenario[] = [
  {
    id: 'gridshot',
    title: 'Gridshot',
    description: 'Classic 3x3 static grid. Shoot targets as fast as possible. 60s speed/accuracy.',
    mode: 'gridshot',
    durationSec: 60,
    targetSize: 0.32,
    targetSizeMax: 0.32,
    targetShape: 'sphere',
    spawnArea: { ...box },
    spawnPattern: 'grid',
    targetCount: 3,
    targetLifetimeMs: 0,
    movementProfile: 'static',
    minSpeed: 0,
    maxSpeed: 0,
    health: 1,
    headshotMultiplier: 1,
    weapon: {
      fireMode: 'click',
      rpm: 600,
      recoilDeg: 0,
      spreadDeg: 0,
      magazine: 30,
      reloadMs: 800,
    },
    scoringWeights: { accuracy: 1, speed: 1.2, precision: 0.8 },
    difficultyScaling: { enabled: false, adjustEverySec: 15, sizeFactor: 0.95, speedFactor: 1.05 },
    gridCols: 3,
    gridRows: 3,
  },
  {
    id: 'spidershot',
    title: 'Spidershot',
    description:
      'Single target spawns at random positions in the FOV cone. Measures reaction + accuracy.',
    mode: 'spidershot',
    durationSec: 60,
    targetSize: 0.35,
    targetSizeMax: 0.35,
    targetShape: 'sphere',
    spawnArea: { ...cone },
    spawnPattern: 'random',
    targetCount: 1,
    targetLifetimeMs: 4000,
    movementProfile: 'static',
    minSpeed: 0,
    maxSpeed: 0,
    health: 1,
    headshotMultiplier: 1,
    weapon: {
      fireMode: 'click',
      rpm: 600,
      recoilDeg: 0,
      spreadDeg: 0,
      magazine: 30,
      reloadMs: 800,
    },
    scoringWeights: { accuracy: 1.2, speed: 1, precision: 1 },
    difficultyScaling: { enabled: true, adjustEverySec: 15, sizeFactor: 0.95, speedFactor: 1 },
  },
  {
    id: 'microshot',
    title: 'Microshot',
    description: 'Tiny targets at long range. Pure precision training.',
    mode: 'microshot',
    durationSec: 60,
    targetSize: 0.14,
    targetSizeMax: 0.16,
    targetShape: 'sphere',
    spawnArea: {
      volume: 'box',
      halfExtents: { x: 5, y: 3.5, z: 0.5 },
      minDistance: 20,
      maxDistance: 30,
    },
    spawnPattern: 'random',
    targetCount: 2,
    targetLifetimeMs: 0,
    movementProfile: 'static',
    minSpeed: 0,
    maxSpeed: 0,
    health: 1,
    headshotMultiplier: 1,
    weapon: {
      fireMode: 'click',
      rpm: 600,
      recoilDeg: 0,
      spreadDeg: 0,
      magazine: 30,
      reloadMs: 800,
    },
    scoringWeights: { accuracy: 1, speed: 0.7, precision: 1.5 },
    difficultyScaling: { enabled: false, adjustEverySec: 15, sizeFactor: 0.95, speedFactor: 1.05 },
  },
  {
    id: 'tracking-motion',
    title: 'Tracking (Motion)',
    description:
      'Continuously moving target. Hold your crosshair on it — time-on-target % sampled every tick.',
    mode: 'tracking',
    durationSec: 60,
    targetSize: 0.4,
    targetSizeMax: 0.4,
    targetShape: 'sphere',
    spawnArea: { ...box },
    spawnPattern: 'random',
    targetCount: 1,
    targetLifetimeMs: 0,
    movementProfile: 'sine',
    minSpeed: 2,
    maxSpeed: 4,
    health: 999,
    headshotMultiplier: 1,
    weapon: { fireMode: 'auto', rpm: 600, recoilDeg: 0, spreadDeg: 0, magazine: 999, reloadMs: 0 },
    scoringWeights: { accuracy: 1, speed: 0.6, precision: 1.2 },
    difficultyScaling: { enabled: true, adjustEverySec: 15, sizeFactor: 1, speedFactor: 1.08 },
  },
  {
    id: 'switching',
    title: 'Switching',
    description: 'Two targets alternate left-right. Measures flick time between switches.',
    mode: 'switching',
    durationSec: 60,
    targetSize: 0.32,
    targetSizeMax: 0.32,
    targetShape: 'sphere',
    spawnArea: { ...box },
    spawnPattern: 'pairs',
    targetCount: 2,
    targetLifetimeMs: 0,
    movementProfile: 'static',
    minSpeed: 0,
    maxSpeed: 0,
    health: 1,
    headshotMultiplier: 1,
    weapon: {
      fireMode: 'click',
      rpm: 600,
      recoilDeg: 0,
      spreadDeg: 0,
      magazine: 30,
      reloadMs: 800,
    },
    scoringWeights: { accuracy: 1, speed: 1.3, precision: 0.9 },
    difficultyScaling: { enabled: false, adjustEverySec: 15, sizeFactor: 0.95, speedFactor: 1.05 },
  },
  {
    id: 'reflex-reactive',
    title: 'Reflex / Reactive',
    description: 'Targets pop up at random delays. Pure reaction time (ms).',
    mode: 'reflex',
    durationSec: 60,
    targetSize: 0.34,
    targetSizeMax: 0.34,
    targetShape: 'sphere',
    spawnArea: { ...cone },
    spawnPattern: 'random',
    targetCount: 1,
    targetLifetimeMs: 2500,
    movementProfile: 'static',
    minSpeed: 0,
    maxSpeed: 0,
    health: 1,
    headshotMultiplier: 1,
    weapon: {
      fireMode: 'click',
      rpm: 600,
      recoilDeg: 0,
      spreadDeg: 0,
      magazine: 30,
      reloadMs: 800,
    },
    scoringWeights: { accuracy: 0.8, speed: 1.5, precision: 0.8 },
    difficultyScaling: { enabled: true, adjustEverySec: 15, sizeFactor: 0.97, speedFactor: 1 },
  },
  {
    id: 'strafe-track',
    title: 'Strafe Track',
    description: 'Target strafes with an unpredictable AI pattern. Read + track simultaneously.',
    mode: 'strafe-track',
    durationSec: 60,
    targetSize: 0.38,
    targetSizeMax: 0.38,
    targetShape: 'capsule',
    spawnArea: { ...box },
    spawnPattern: 'random',
    targetCount: 1,
    movementProfile: 'strafe-ai',
    targetLifetimeMs: 0,
    minSpeed: 3,
    maxSpeed: 6,
    health: 999,
    headshotMultiplier: 1,
    weapon: { fireMode: 'auto', rpm: 600, recoilDeg: 0, spreadDeg: 0, magazine: 999, reloadMs: 0 },
    scoringWeights: { accuracy: 1, speed: 0.7, precision: 1.2 },
    difficultyScaling: { enabled: true, adjustEverySec: 15, sizeFactor: 1, speedFactor: 1.08 },
  },
  {
    id: 'target-switching-speed',
    title: 'Target Switching Speed',
    description: 'Many targets on screen at once. Prioritize and clear them fast.',
    mode: 'target-switching-speed',
    durationSec: 60,
    targetSize: 0.3,
    targetSizeMax: 0.3,
    targetShape: 'sphere',
    spawnArea: { ...box },
    spawnPattern: 'random',
    targetCount: 5,
    targetLifetimeMs: 0,
    movementProfile: 'static',
    minSpeed: 0,
    maxSpeed: 0,
    health: 1,
    headshotMultiplier: 1,
    weapon: {
      fireMode: 'click',
      rpm: 600,
      recoilDeg: 0,
      spreadDeg: 0,
      magazine: 30,
      reloadMs: 800,
    },
    scoringWeights: { accuracy: 1, speed: 1.4, precision: 0.8 },
    difficultyScaling: { enabled: false, adjustEverySec: 15, sizeFactor: 0.95, speedFactor: 1.05 },
  },
  {
    id: 'sandbox',
    title: 'Custom / Sandbox',
    description: 'Every parameter is user-adjustable. Author your own drill.',
    mode: 'custom',
    durationSec: 60,
    targetSize: 0.3,
    targetSizeMax: 0.45,
    targetShape: 'sphere',
    spawnArea: { ...box },
    spawnPattern: 'random',
    targetCount: 3,
    targetLifetimeMs: 0,
    movementProfile: 'linear',
    minSpeed: 1,
    maxSpeed: 3,
    health: 1,
    headshotMultiplier: 1,
    weapon: {
      fireMode: 'click',
      rpm: 600,
      recoilDeg: 0,
      spreadDeg: 0,
      magazine: 30,
      reloadMs: 800,
    },
    scoringWeights: { accuracy: 1, speed: 1, precision: 1 },
    difficultyScaling: { enabled: false, adjustEverySec: 15, sizeFactor: 0.95, speedFactor: 1.05 },
  },
];
